require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AddonsController do

  # This should return the minimal set of attributes required to create a valid
  # Addon. As you add validations to Addon, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all addons as @addons" do
      addon = Addon.create! valid_attributes
      get :index
      assigns(:addons).should eq([addon])
    end
  end

  describe "GET show" do
    it "assigns the requested addon as @addon" do
      addon = Addon.create! valid_attributes
      get :show, :id => addon.id.to_s
      assigns(:addon).should eq(addon)
    end
  end

  describe "GET new" do
    it "assigns a new addon as @addon" do
      get :new
      assigns(:addon).should be_a_new(Addon)
    end
  end

  describe "GET edit" do
    it "assigns the requested addon as @addon" do
      addon = Addon.create! valid_attributes
      get :edit, :id => addon.id.to_s
      assigns(:addon).should eq(addon)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Addon" do
        expect {
          post :create, :addon => valid_attributes
        }.to change(Addon, :count).by(1)
      end

      it "assigns a newly created addon as @addon" do
        post :create, :addon => valid_attributes
        assigns(:addon).should be_a(Addon)
        assigns(:addon).should be_persisted
      end

      it "redirects to the created addon" do
        post :create, :addon => valid_attributes
        response.should redirect_to(Addon.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved addon as @addon" do
        # Trigger the behavior that occurs when invalid params are submitted
        Addon.any_instance.stub(:save).and_return(false)
        post :create, :addon => {}
        assigns(:addon).should be_a_new(Addon)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Addon.any_instance.stub(:save).and_return(false)
        post :create, :addon => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested addon" do
        addon = Addon.create! valid_attributes
        # Assuming there are no other addons in the database, this
        # specifies that the Addon created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Addon.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => addon.id, :addon => {'these' => 'params'}
      end

      it "assigns the requested addon as @addon" do
        addon = Addon.create! valid_attributes
        put :update, :id => addon.id, :addon => valid_attributes
        assigns(:addon).should eq(addon)
      end

      it "redirects to the addon" do
        addon = Addon.create! valid_attributes
        put :update, :id => addon.id, :addon => valid_attributes
        response.should redirect_to(addon)
      end
    end

    describe "with invalid params" do
      it "assigns the addon as @addon" do
        addon = Addon.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Addon.any_instance.stub(:save).and_return(false)
        put :update, :id => addon.id.to_s, :addon => {}
        assigns(:addon).should eq(addon)
      end

      it "re-renders the 'edit' template" do
        addon = Addon.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Addon.any_instance.stub(:save).and_return(false)
        put :update, :id => addon.id.to_s, :addon => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested addon" do
      addon = Addon.create! valid_attributes
      expect {
        delete :destroy, :id => addon.id.to_s
      }.to change(Addon, :count).by(-1)
    end

    it "redirects to the addons list" do
      addon = Addon.create! valid_attributes
      delete :destroy, :id => addon.id.to_s
      response.should redirect_to(addons_url)
    end
  end

end
