require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe NewspostsController do

  # This should return the minimal set of attributes required to create a valid
  # Newspost. As you add validations to Newspost, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all newsposts as @newsposts" do
      newspost = Newspost.create! valid_attributes
      get :index
      assigns(:newsposts).should eq([newspost])
    end
  end

  describe "GET show" do
    it "assigns the requested newspost as @newspost" do
      newspost = Newspost.create! valid_attributes
      get :show, :id => newspost.id.to_s
      assigns(:newspost).should eq(newspost)
    end
  end

  describe "GET new" do
    it "assigns a new newspost as @newspost" do
      get :new
      assigns(:newspost).should be_a_new(Newspost)
    end
  end

  describe "GET edit" do
    it "assigns the requested newspost as @newspost" do
      newspost = Newspost.create! valid_attributes
      get :edit, :id => newspost.id.to_s
      assigns(:newspost).should eq(newspost)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Newspost" do
        expect {
          post :create, :newspost => valid_attributes
        }.to change(Newspost, :count).by(1)
      end

      it "assigns a newly created newspost as @newspost" do
        post :create, :newspost => valid_attributes
        assigns(:newspost).should be_a(Newspost)
        assigns(:newspost).should be_persisted
      end

      it "redirects to the created newspost" do
        post :create, :newspost => valid_attributes
        response.should redirect_to(Newspost.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved newspost as @newspost" do
        # Trigger the behavior that occurs when invalid params are submitted
        Newspost.any_instance.stub(:save).and_return(false)
        post :create, :newspost => {}
        assigns(:newspost).should be_a_new(Newspost)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Newspost.any_instance.stub(:save).and_return(false)
        post :create, :newspost => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested newspost" do
        newspost = Newspost.create! valid_attributes
        # Assuming there are no other newsposts in the database, this
        # specifies that the Newspost created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Newspost.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => newspost.id, :newspost => {'these' => 'params'}
      end

      it "assigns the requested newspost as @newspost" do
        newspost = Newspost.create! valid_attributes
        put :update, :id => newspost.id, :newspost => valid_attributes
        assigns(:newspost).should eq(newspost)
      end

      it "redirects to the newspost" do
        newspost = Newspost.create! valid_attributes
        put :update, :id => newspost.id, :newspost => valid_attributes
        response.should redirect_to(newspost)
      end
    end

    describe "with invalid params" do
      it "assigns the newspost as @newspost" do
        newspost = Newspost.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Newspost.any_instance.stub(:save).and_return(false)
        put :update, :id => newspost.id.to_s, :newspost => {}
        assigns(:newspost).should eq(newspost)
      end

      it "re-renders the 'edit' template" do
        newspost = Newspost.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Newspost.any_instance.stub(:save).and_return(false)
        put :update, :id => newspost.id.to_s, :newspost => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested newspost" do
      newspost = Newspost.create! valid_attributes
      expect {
        delete :destroy, :id => newspost.id.to_s
      }.to change(Newspost, :count).by(-1)
    end

    it "redirects to the newsposts list" do
      newspost = Newspost.create! valid_attributes
      delete :destroy, :id => newspost.id.to_s
      response.should redirect_to(newsposts_url)
    end
  end

end
